# This is a basic workflow to help you get started with Actions

name: Emulator tests

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [30]
        # target: [google_apis]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: set up JDK 1.19
        uses: actions/setup-java@v4
        with:
          java-version: '19'
          distribution: zulu
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Create empty keystore
        run: echo "storeFile=/" > keystore.properties
      - name: Android Emulator Runner
        uses: ReactiveCircus/android-emulator-runner@v2.30.1
        with:
          api-level: ${{ matrix.api-level }}
          # target: ${{ matrix.target }}
          arch: x86_64
#           emulator-build: 7075546
          script: './gradlew connectedFullDebugAndroidTest'
